### ISSUE TITLE
Add support for fish

### ISSUE THREAD

**Issue by jamesmunns** [jamesmunns/shell-hist#1]
TODO:

1. get example of fish history
2. get fish history path
3. add flag parsing to [here](https://github.com/jamesmunns/shell-hist/blob/master/src/opts.rs#L37-L65) and [here](https://github.com/jamesmunns/shell-hist/blob/master/src/parse.rs#L170-L177)

**Comment by chriskrycho** [comment]
Fish history locations, per [here](https://github.com/fish-shell/fish-shell/issues/862#issuecomment-19138822):

- `~/.local/share/fish/fish_history` for versions >= 2.3.0
- `~/.config/fish/fish_history` for versions < 2.3.0

Fish history example:

```
- cmd: git --help
  when: 1547677106
- cmd: brew install fish ripgrep
  when: 1547677106
- cmd: brew install hub
  when: 1547677106
- cmd: chsh -s /usr/local/bin/fish
  when: 1547677106
- cmd: mkdir ~/.config/fish
  when: 1547677132
- cmd: cd tools/
  when: 1547682095
  paths:
    - tools/
- cmd: git clone git@github.com:chriskrycho/evernote-to-bear.git
  when: 1547682097
- cmd: cd evernote-to-bear/
  when: 1547682104
  paths:
    - evernote-to-bear/
```

This *appears* to be YAML (or YAML-like?), but I haven't been able to confirm that with my 3 minutes of poking. I also haven't found any keys besides `cmd`, `when`, and `paths` in my own history. It looks like, for the purposes of this tool, it's just a YAML hash with those three keys and you could just drop everything but the value of the `cmd` key.
